/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/


#ifndef FitFunctionPDF_h
#define FitFunctionPDF_h


#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "FitFunction.hh"


#include <complex>
#include "RooFormulaVar.h"


class FitFunctionPDF : public RooAbsPdf
{
public:
   FitFunctionPDF() {}
   FitFunctionPDF(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2,
        RooAbsReal& _norm_Systematic,
        RooAbsReal& _shape_Systematic,
        FitFunction function);
  FitFunctionPDF(FitFunctionPDF const &other, const char *name=nullptr);


  double evaluate() const override;
  RooFormulaVar signal_norm(std::string channel_name);
protected:


  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy branch_ratio_1 ;
  RooRealProxy branch_ratio_2 ;
  RooRealProxy norm_Systematic ;
  RooRealProxy shape_Systematic ;


 
private:
  FitFunction function;

  ClassDefOverride(FitFunctionPDF, 1) // Your description goes here...
};





#endif // FitFunctionPDF_h