/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/


#include "../interface/FitFunctionPDF.h"
#include "TBufferFile.h"
#include "TClass.h"

#include <algorithm>
#include <cmath>
#include <set>
#include <stdexcept>
#include <utility>


ClassImp(FitFunctionPDF);


FitFunctionPDF::FitFunctionPDF(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _realHiggsMass,
                        RooAbsReal& _branch_ratio_1,
                        RooAbsReal& _branch_ratio_2,
                        RooAbsReal& _norm_Systematic,
                        RooAbsReal& _shape_Systematic,
                        std::shared_ptr<FitFunction> model)
   : RooAbsPdf(name,title),
   x("x","x",this,_x),
   realHiggsMass("realHiggsMass","realHiggsMass",this,_realHiggsMass),
   branch_ratio_1("branch_ratio_1","branch_ratio_1",this,_branch_ratio_1),
   branch_ratio_2("branch_ratio_2","branch_ratio_2",this,_branch_ratio_2),
   norm_Systematic("norm_Systematic","norm_Systematic",this,_norm_Systematic),
   shape_Systematic("shape_Systematic","shape_Systematic",this,_shape_Systematic),
   function(std::move(model))
{
   if (!function)
      throw std::invalid_argument("FitFunctionPDF requires a model");
}


FitFunctionPDF::FitFunctionPDF(const char *name, const char *title,
                        RooAbsReal& _x, RooAbsReal& _realHiggsMass,
                        RooAbsReal& _branch_ratio_1, RooAbsReal& _branch_ratio_2,
                        RooAbsReal& _norm_Systematic, RooAbsReal& _shape_Systematic,
                        std::shared_ptr<FitFunction> model,
                        const std::vector<std::string>& systematicNames,
                        const RooArgList& deltas)
   : FitFunctionPDF(name, title, _x, _realHiggsMass, _branch_ratio_1,
                    _branch_ratio_2, _norm_Systematic, _shape_Systematic, std::move(model))
{
   // need to check
   if (systematicNames.size() != static_cast<std::size_t>(deltas.getSize()))
      throw std::invalid_argument("Systematic names must match the delta list");

   std::set<std::string> seen;
   const auto availableSystematics = function->listSystematics();
   for (std::size_t i = 0; i < systematicNames.size(); ++i)
   {
      // add sys names/dels in right manner
      const auto& systematic = systematicNames[i];
      const auto* delta = dynamic_cast<const RooAbsReal*>(deltas.at(static_cast<int>(i)));
      if (!delta || shape_Systematics.find(delta->GetName()))
         throw std::invalid_argument("Shape deltas must be RooAbsReal objects with unique names");
      if (!seen.insert(systematic).second)
         throw std::invalid_argument("Duplicate shape systematic: " + systematic);
      if (std::find(availableSystematics.begin(), availableSystematics.end(), systematic) == availableSystematics.end())
         throw std::invalid_argument("Unknown or incomplete shape systematic: " + systematic);
      shapeSystematicNames.push_back(systematic);
      shape_Systematics.add(*delta);
   }
}


FitFunctionPDF::FitFunctionPDF(FitFunctionPDF const &other, const char *name)
   : RooAbsPdf(other,name),
   x("x",this,other.x),
   realHiggsMass("realHiggsMass",this,other.realHiggsMass),
   branch_ratio_1("branch_ratio_1",this,other.branch_ratio_1),
   branch_ratio_2("branch_ratio_2",this,other.branch_ratio_2),
   norm_Systematic("norm_Systematic",this,other.norm_Systematic),
   shape_Systematic("shape_Systematic",this,other.shape_Systematic),
   shape_Systematics("shape_Systematics",this,other.shape_Systematics),
   function(other.function),
   shapeSystematicNames(other.shapeSystematicNames)
{
}






double FitFunctionPDF::evaluate() const
{
   FitFunction::NuisanceValues nuisances;
   for (std::size_t i = 0; i < shapeSystematicNames.size(); ++i)
   {
      // need to read the proxy in case of clone or imported pdfs can use redir'd nusiances
      // better way to do?
      const double delta = static_cast<const RooAbsReal*>(shape_Systematics.at(static_cast<int>(i)))->getVal();
      if (!std::isfinite(delta))
         throw std::invalid_argument("Shape-systematic deltas must be finite");
      nuisances.emplace(shapeSystematicNames[i], delta);
   }
   return function->evaluate(x.arg().getVal(), realHiggsMass.arg().getVal(), nuisances);
}


RooFormulaVar FitFunctionPDF::signal_norm(std::string channel_name) const
{
   std::string normExpression = "@1 * (" + function->getNormExpression("@0") + ")";
   std::string normName = channel_name + "_norm";

   return RooFormulaVar(normName.c_str(), normName.c_str(), normExpression.c_str(),
                        RooArgList(*realHiggsMass.absArg(), *norm_Systematic.absArg()));
}

// we have to do this custom because root doesnt support shr ptr io
// see https://root.cern.ch/manual/io_custom_classes/#restrictions-on-types-root-io-can-handle
void FitFunctionPDF::Streamer(TBuffer &buffer)
{
   const auto *modelClass = TClass::GetClass(typeid(FitFunction));
   if (buffer.IsReading())
   {
      UInt_t start, count;
      const auto version = buffer.ReadVersion(&start, &count);
      if (version < 4)
         throw std::runtime_error("You're working with the older version, plz move to the new one with the shared model fitfunctionpdf for this to work");
      buffer.ReadClassBuffer(FitFunctionPDF::Class(), this, version, start, count);
      std::string data;
      buffer.ReadStdString(&data);
      TBufferFile modelBuffer(TBuffer::kRead, data.size(), data.data(), false);
      function.reset(static_cast<FitFunction*>(modelBuffer.ReadObjectAny(modelClass)));
      if (!function)
         throw std::runtime_error("Can't read the FitFunctionPDF model");
   }
   else
   {
      if (!function)
         throw std::runtime_error("Can't write a FitFunctionPDF without a model");
      buffer.WriteClassBuffer(FitFunctionPDF::Class(), this);
      // the best way to do this appears to be having both PDF pass an
      // their own status of the model
      // we can avoid two shr_ptr blocks having the same root object with a seperate buffer

      TBufferFile modelBuffer(TBuffer::kWrite);
      modelBuffer.WriteObjectAny(function.get(), modelClass);
      const std::string data(modelBuffer.Buffer(), modelBuffer.Length());
      buffer.WriteStdString(&data);
   }
}
