/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/


#ifndef FitFunctionPDF_h
#define FitFunctionPDF_h


#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooArgList.h"
#include "RooListProxy.h"
#include "RooAbsReal.h"
#include "CMSAnalysis/Analysis/interface/FitFunction.hh"


#include <memory>
#include <string>
#include <vector>
#include "RooFormulaVar.h"


class FitFunctionPDF : public RooAbsPdf
{
public:
   FitFunctionPDF() {}
   FitFunctionPDF(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2,
        RooAbsReal& _norm_Systematic,
        RooAbsReal& _shape_Systematic,
        std::shared_ptr<FitFunction> function);
   FitFunctionPDF(const char *name, const char *title, RooAbsReal& _x,
        RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2,
        RooAbsReal& _norm_Systematic,
        RooAbsReal& _shape_Systematic,
        std::shared_ptr<FitFunction> function,
        const std::vector<std::string>& systematicNames,
        const RooArgList& deltas);
  FitFunctionPDF(FitFunctionPDF const &other, const char *name=nullptr);
  TObject *clone(const char *newName) const override { return new FitFunctionPDF(*this, newName); }


  double evaluate() const override;
  RooFormulaVar signal_norm(std::string channel_name) const;
protected:


  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy branch_ratio_1 ;
  RooRealProxy branch_ratio_2 ;
  RooRealProxy norm_Systematic ;
  RooRealProxy shape_Systematic ;
  RooListProxy shape_Systematics{"shape_Systematics", "shape_Systematics", this};


 
private:
  std::shared_ptr<FitFunction> function; //! note that we have the custom impl for this since shr ptr io doesnt work
  std::vector<std::string> shapeSystematicNames;

  ClassDefOverride(FitFunctionPDF, 4)
};





#endif // FitFunctionPDF_h
