/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "RooPDF_HiggsAnalysis_BKG.h"

#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <Riostream.h>
#include <TMath.h>
#include <RooGenericPdf.h>
#include <cmath>

// Indices in bkg_params for each type of background
static const int I_TTBAR = 1;
static const int I_ZZ = 2;
static const int I_DY = 0;
static const int I_TTZ = 3;


ClassImp(RooPDF_HiggsAnalysis_BKG);

RooPDF_HiggsAnalysis_BKG::RooPDF_HiggsAnalysis_BKG(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _realHiggsMass,
                        RooAbsReal& _branch_ratio_1,
                        RooAbsReal& _branch_ratio_2,
                        RooAbsReal& _norm_Systematic,
                        RooAbsReal& _shape_Systematic,
                        const std::vector<std::vector<double>>& _bkg_params,
                        const std::string _channel_name)
   : RooPDF_HiggsAnalysis_Base(name, title, _x, _realHiggsMass, _branch_ratio_1, _branch_ratio_2, _norm_Systematic, _shape_Systematic),
   x("x","x",this,_x),
   realHiggsMass("realHiggsMass","realHiggsMass",this,_realHiggsMass),
   branch_ratio_1("branch_ratio_1","branch_ratio_1",this,_branch_ratio_1),
   branch_ratio_2("branch_ratio_2","branch_ratio_2",this,_branch_ratio_2),
   norm_Systematic("norm_Systematic","norm_Systematic",this,_norm_Systematic),
   shape_Systematic("shape_Systematic","shape_Systematic",this,_shape_Systematic),
   bkg_params(_bkg_params),
   channel_name(_channel_name)
{
}

RooPDF_HiggsAnalysis_BKG::RooPDF_HiggsAnalysis_BKG(RooPDF_HiggsAnalysis_BKG const &other, const char *name)
   : RooPDF_HiggsAnalysis_Base(other,name),
   x("x",this,other.x),
   realHiggsMass("realHiggsMass",this,other.realHiggsMass),
   branch_ratio_1("branch_ratio_1",this,other.branch_ratio_1),
   branch_ratio_2("branch_ratio_2",this,other.branch_ratio_2),
   norm_Systematic("norm_Systematic",this,other.norm_Systematic),
   shape_Systematic("shape_Systematic",this,other.shape_Systematic),
   bkg_params(other.bkg_params),
   channel_name(other.channel_name)
{
}

RooFormulaVar RooPDF_HiggsAnalysis_BKG::signal_norm(std::string channel_name)
 {
    return RooFormulaVar();
 }

 RooGenericPdf RooPDF_HiggsAnalysis_BKG::ttbar()
 {
  std::vector<double> bkg_type = bkg_params[I_TTBAR];
  std::string bkg_Function = std::to_string(bkg_type[0]) + "* (@0-" + std::to_string(bkg_type[1]) + ")^" + std::to_string(bkg_type[2]);
  RooGenericPdf bkg_ttbar((channel_name + "_bkg_ttbar").c_str(), bkg_Function.c_str(), RooArgSet(*x.absArg()));
  return bkg_ttbar;
 }

 RooGenericPdf RooPDF_HiggsAnalysis_BKG::ZZ()
 {
  std::vector<double> bkg_type = bkg_params[I_ZZ];
  std::string bkg_Function = std::to_string(bkg_type[0]) + "* (@0-" + std::to_string(bkg_type[1]) + ")^" + std::to_string(bkg_type[2]);
  RooGenericPdf bkg_ZZ((channel_name + "_bkg_ZZ").c_str(), bkg_Function.c_str(), RooArgSet(*x.absArg()));
  return bkg_ZZ;
 }

 RooGenericPdf RooPDF_HiggsAnalysis_BKG::DY()
 {
  std::vector<double> bkg_type = bkg_params[I_DY];
  std::string bkg_Function = std::to_string(bkg_type[0]) + "* (@0-" + std::to_string(bkg_type[1]) + ")^" + std::to_string(bkg_type[2]);
  RooGenericPdf bkg_DY((channel_name + "_bkg_DY").c_str(), bkg_Function.c_str(), RooArgSet(*x.absArg()));
  return bkg_DY;
 }

 RooGenericPdf RooPDF_HiggsAnalysis_BKG::TTZ()
 {
  std::vector<double> bkg_type = bkg_params[I_TTZ];
  std::string bkg_Function = std::to_string(bkg_type[0]) + "* (@0-" + std::to_string(bkg_type[1]) + ")^" + std::to_string(bkg_type[2]);
  RooGenericPdf bkg_TTZ((channel_name + "_bkg_TTZ").c_str(), bkg_Function.c_str(), RooArgSet(*x.absArg()));
  return bkg_TTZ;
 }


double RooPDF_HiggsAnalysis_BKG::evaluate() const 
{ 
//std::cout << "Starting evaluate()\n";
std::vector<double> component_functions;
double function_sum = 0;
for (std::vector<double> bkg_type : bkg_params)
{
   if (bkg_type.size() < 2)
   {
   continue;
   }
   //std::cerr << "Next loop iteration\n";
   //std::cerr << bkg_type[0] << '\n' << bkg_type[1] << '\n' << bkg_type[2] <<'\n';

   //std::cout << "BKG Components: " << bkg_type[0] << " " << bkg_type[1] << " " << bkg_type[2] << "\n";



   double bkg_component = bkg_type[0] * std::pow((x - bkg_type[1]),bkg_type[2]);
   bool isNaN = std::isnan(bkg_component);
   if (isNaN)
   {
   //std::cout << "NaN value from evaluating " << bkg_type[0] << " * " << "(" << x << "-" << bkg_type[1] << ")^" << bkg_type[2] << "\n";
   }
   // else
   // {
   //   std::cout << "Is a number" << "\n";
   // }
   //bool secondInvalidValueTest = bkg_type[2] <= 0;
   //std::cout << "Test statement: " << invalidValueTest << "\n";
   component_functions.push_back(bkg_component);
   function_sum += bkg_component;
}
//std::cout << GetName() << " bkg function_sum: " << function_sum << "\n";
//std::cout << "\n \n \n";
return function_sum; 
} 

