/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooPDF_HiggsAnalysis_DBLGAUSS_h
#define RooPDF_HiggsAnalysis_DBLGAUSS_h

#include <RooPDF_HiggsAnalysis_Base.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>

class RooPDF_HiggsAnalysis_DBLGAUSS : public RooPDF_HiggsAnalysis_Base {
public:
   RooPDF_HiggsAnalysis_DBLGAUSS() {}
   RooPDF_HiggsAnalysis_DBLGAUSS(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2,
        RooAbsReal& _norm_Systematic,
        RooAbsReal& _shape_Systematic,
        const std::vector<std::vector<double>>& _signal_params,
        bool multiplyBy2);
  RooPDF_HiggsAnalysis_DBLGAUSS(RooPDF_HiggsAnalysis_DBLGAUSS const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooPDF_HiggsAnalysis_DBLGAUSS(*this, newname); }
protected:

  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy branch_ratio_1 ;
  RooRealProxy branch_ratio_2 ;
  RooRealProxy norm_Systematic ;
  RooRealProxy shape_Systematic ;
  const std::vector<std::vector<double>> signal_params;
  bool multiplyBy2;

  double evaluate() const override;

private:

  ClassDefOverride(RooPDF_HiggsAnalysis_DBLGAUSS, 1) // Your description goes here...
};



#endif // RooPDF_HiggsAnalysis_DBLGAUSS_h