/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooPDF_HiggsAnalysis_BKG_h
#define RooPDF_HiggsAnalysis_BKG_h

#include "RooPDF_HiggsAnalysis_Base.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooGenericPdf.h"

#include <complex>

class RooPDF_HiggsAnalysis_BKG : public RooPDF_HiggsAnalysis_Base {
public:
   RooPDF_HiggsAnalysis_BKG() {}
   RooPDF_HiggsAnalysis_BKG(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2,
        RooAbsReal& _norm_Systematic,
        RooAbsReal& _shape_Systematic,
        const std::vector<std::vector<double>>& _bkg_params, 
        const std::string _channel_name);
  RooPDF_HiggsAnalysis_BKG(RooPDF_HiggsAnalysis_BKG const &other, const char *name=nullptr);
  virtual RooFormulaVar signal_norm(std::string channel_name) override;
  RooGenericPdf ttbar();
  RooGenericPdf ZZ();
  RooGenericPdf DY();
  RooGenericPdf TTZ();

  TObject* clone(const char *newname) const override { return new RooPDF_HiggsAnalysis_BKG(*this, newname); }
protected:

  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy branch_ratio_1 ;
  RooRealProxy branch_ratio_2 ;
  RooRealProxy norm_Systematic ;
  RooRealProxy shape_Systematic ;
  const std::vector<std::vector<double>> bkg_params;
  const std::string channel_name;


  double evaluate() const override;

private:

  ClassDefOverride(RooPDF_HiggsAnalysis_BKG, 1) // Your description goes here...
};



#endif // RooPDF_HiggsAnalysis_BKG_h