/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/


#ifndef RooPDF_HiggsAnalysis_DSCB_h
#define RooPDF_HiggsAnalysis_DSCB_h


#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooPDF_HiggsAnalysis_Base.h"
#include <complex>
#include "RooFormulaVar.h"


class RooPDF_HiggsAnalysis_DSCB : public RooPDF_HiggsAnalysis_Base {
public:
   RooPDF_HiggsAnalysis_DSCB() {}
   RooPDF_HiggsAnalysis_DSCB(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2,
        RooAbsReal& _norm_Systematic,
        RooAbsReal& _shape_Systematic,
        const std::vector<std::vector<double>>& _signal_params,
        bool multiplyBy2);
  RooPDF_HiggsAnalysis_DSCB(RooPDF_HiggsAnalysis_DSCB const &other, const char *name=nullptr);
  virtual RooFormulaVar signal_norm(std::string channel_name) override;


  TObject* clone(const char *newname) const override { return new RooPDF_HiggsAnalysis_DSCB(*this, newname); }
protected:


  std::vector<std::vector<double>> signal_params;
  bool multiplyBy2;


  double evaluate() const override;




private:


  ClassDefOverride(RooPDF_HiggsAnalysis_DSCB, 1) // Your description goes here...
};




#endif // RooPDF_HiggsAnalysis_DSCB_h