/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPDF_BKG
#define ROOPDF_BKG

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <RooGenericPdf.h>

 
class RooPDF_BKG : public RooAbsPdf {
public:
  RooPDF_BKG() {} ; 
  RooPDF_BKG(const char *name, const char *title,
	      RooAbsReal& _x, 
        const std::vector<std::vector<double>>& _bkg_params, 
        const std::string _channel_name);
  RooPDF_BKG(const RooPDF_BKG& other, const char* name=0) ;
  RooGenericPdf ttbar();
  RooGenericPdf ZZ();
  RooGenericPdf DY();
  RooGenericPdf TTZ();



  virtual TObject* clone(const char* newname) const { return new RooPDF_BKG(*this,newname); }
  inline virtual ~RooPDF_BKG() { }

protected:

  RooRealProxy x ;
  const std::vector<std::vector<double>> bkg_params;
  const std::string channel_name;

  Double_t evaluate() const ;

private:

  ClassDef(RooPDF_BKG,1) // Your description goes here...
};
 
#endif
