/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here...
 

#include "Riostream.h" 

#include "RooPDF_BKG.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include <RooGenericPdf.h>

ClassImp(RooPDF_BKG); 

 RooPDF_BKG::RooPDF_BKG(const char *name, const char *title, 
                        RooAbsReal& _x,
                        const std::vector<std::vector<double>>& _bkg_params,
                        const std::string _channel_name) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   bkg_params(_bkg_params),
   channel_name(_channel_name)
 { 
 } 


 RooPDF_BKG::RooPDF_BKG(const RooPDF_BKG& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   bkg_params(other.bkg_params),
   channel_name(other.channel_name)
 { 
 } 
 
 RooGenericPdf RooPDF_BKG::ttbar()
 {
  std::vector<double> bkg_type = bkg_params[0];
  std::string bkg_Function = std::to_string(bkg_type[0]) + "* (@0-" + std::to_string(bkg_type[1]) + ")^" + std::to_string(bkg_type[2]);
  RooGenericPdf bkg_ttbar((channel_name + "_bkg_ttbar").c_str(), bkg_Function.c_str(), RooArgSet(*x.absArg()));
  return bkg_ttbar;
 }

 RooGenericPdf RooPDF_BKG::ZZ()
 {
  std::vector<double> bkg_type = bkg_params[1];
  std::string bkg_Function = std::to_string(bkg_type[0]) + "* (@0-" + std::to_string(bkg_type[1]) + ")^" + std::to_string(bkg_type[2]);
  RooGenericPdf bkg_ZZ((channel_name + "_bkg_ZZ").c_str(), bkg_Function.c_str(), RooArgSet(*x.absArg()));
  return bkg_ZZ;
 }

 RooGenericPdf RooPDF_BKG::DY()
 {
  std::vector<double> bkg_type = bkg_params[2];
  std::string bkg_Function = std::to_string(bkg_type[0]) + "* (@0-" + std::to_string(bkg_type[1]) + ")^" + std::to_string(bkg_type[2]);
  RooGenericPdf bkg_DY((channel_name + "_bkg_DY").c_str(), bkg_Function.c_str(), RooArgSet(*x.absArg()));
  return bkg_DY;
 }

 RooGenericPdf RooPDF_BKG::TTZ()
 {
  std::vector<double> bkg_type = bkg_params[3];
  std::string bkg_Function = std::to_string(bkg_type[0]) + "* (@0-" + std::to_string(bkg_type[1]) + ")^" + std::to_string(bkg_type[2]);
  RooGenericPdf bkg_TTZ((channel_name + "_bkg_TTZ").c_str(), bkg_Function.c_str(), RooArgSet(*x.absArg()));
  return bkg_TTZ;
 }



 Double_t RooPDF_BKG::evaluate() const 
 { 
  std::vector<double> component_functions;
  double function_sum = 0;
	for (std::vector<double> bkg_type : bkg_params)
	{
	  double bkg_component = bkg_type[0] * std::pow((x - bkg_type[1]),bkg_type[2]);
		component_functions.push_back(bkg_component);
    function_sum += bkg_component;
	}
  
  return function_sum; 
 } 



