/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPDF_DSCB_TEST
#define ROOPDF_DSCB_TEST

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooFormulaVar.h" 

 
class RooPDF_DSCB_test : public RooAbsPdf {
public:
  RooPDF_DSCB_test() {} ; 
  RooPDF_DSCB_test(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _realHiggsMass,
	      RooAbsReal& _branch_ratio_1,
	      RooAbsReal& _branch_ratio_2,
	      RooAbsReal& _norm_Systematic,
	      RooAbsReal& _shape_Systematic,
        const std::vector<std::vector<double>>& _signal_params,
        bool multiplyBy2);
  RooPDF_DSCB_test(const RooPDF_DSCB_test& other, const char* name=0) ;
  RooFormulaVar signal_norm(std::string channel_name);
  double evaluatePowerLaw(double p0, double p1, double p2) const;


  virtual TObject* clone(const char* newname) const { return new RooPDF_DSCB_test(*this,newname); }
  inline virtual ~RooPDF_DSCB_test() { }

protected:

  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy branch_ratio_1 ;
  RooRealProxy branch_ratio_2 ;
  RooRealProxy norm_Systematic ;
  RooRealProxy shape_Systematic ;
  const std::vector<std::vector<double>> signal_params;
  bool multiplyBy2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooPDF_DSCB_test,1) // Your description goes here...
};
 
#endif
