/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooPDF_BKG_DeltaAdditionTest_h
#define RooPDF_BKG_DeltaAdditionTest_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>

class RooPDF_BKG_DeltaAdditionTest : public RooAbsPdf {
public:
   RooPDF_BKG_DeltaAdditionTest() {}
   RooPDF_BKG_DeltaAdditionTest(const char *name, const char *title,        RooAbsReal& _x, const double _delta, const std::vector<std::vector<double>>& _bkg_params,
                        const std::vector<std::vector<double>>& _bkg_paramUpperValues,
                        const std::vector<std::vector<double>>& _bkg_paramLowerValues,
                        const std::string _channel_name);
  RooPDF_BKG_DeltaAdditionTest(RooPDF_BKG_DeltaAdditionTest const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooPDF_BKG_DeltaAdditionTest(*this, newname); }
  RooGenericPdf ttbar();
  RooGenericPdf ZZ();
  RooGenericPdf DY();
  RooGenericPdf TTZ();
protected:

  RooRealProxy x ;
  const double delta;
  const std::vector<std::vector<double>> bkg_params;
  const std::vector<std::vector<double>> bkg_paramUpperValues;
  const std::vector<std::vector<double>> bkg_paramLowerValues;
  const std::string channel_name;
  double evaluate() const override;
  std::vector<double> AddUncertaintyToParams(std::vector<double> originalParams);
  void computeBatch(double* output, std::size_t size, RooFit::Detail::DataMap const&) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooPDF_BKG_DeltaAdditionTest, 1) // Your description goes here...
};
inline double RooPDF_BKG_DeltaAdditionTest_evaluate(double x) 
{
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE

   return 1.0; 
}


#endif // RooPDF_BKG_DeltaAdditionTest_h