/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooPDF_DSCB_h
#define RooPDF_DSCB_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>

class RooPDF_DSCB : public RooAbsPdf {
public:
   RooPDF_DSCB() {}
   RooPDF_DSCB(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2);
  RooPDF_DSCB(RooPDF_DSCB const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooPDF_DSCB(*this, newname); }
protected:

  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy branch_ratio_1 ;
  RooRealProxy branch_ratio_2 ;

  double evaluate() const override;
  void computeBatch(double* output, std::size_t size, RooFit::Detail::DataMap const&) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooPDF_DSCB, 1) // Your description goes here...
};
inline double RooPDF_DSCB_evaluate(double x, double realHiggsMass, double branch_ratio_1, double branch_ratio_2) 
{
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE

   return 1.0; 
}


#endif // RooPDF_DSCB_h