/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPDF_DSCB
#define ROOPDF_DSCB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooFormulaVar.h" 

 
class RooPDF_DSCB : public RooAbsPdf {
public:
  RooPDF_DSCB() {} ; 
  RooPDF_DSCB(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2,
        const std::vector<std::vector<double>>& _signal_params,
        bool multiplyBy2);

  RooPDF_DSCB(const RooPDF_DSCB& other, const char* name=0) ;
  RooFormulaVar signal_norm(std::string channel_name);



  virtual TObject* clone(const char* newname) const { return new RooPDF_DSCB(*this,newname); }
  inline virtual ~RooPDF_DSCB() { }
  void printParameters();


protected:

  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy branch_ratio_1 ;
  RooRealProxy branch_ratio_2 ;
  const std::vector<std::vector<double>> signal_params;
  bool multiplyBy2;
   
  Double_t evaluate() const ;

private:

  ClassDef(RooPDF_DSCB,1) // Your description goes here...
};
 
#endif
