// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /uscms/home/kponx/CMSSW_11_3_4/src/HiggsAnalysis/CombinedLimit/data/tutorials/parametric_exercise/combinetutorial-2023-parametric/./RooPDF_BKG.h;
#pragma link C++ defined_in "/uscms/home/kponx/CMSSW_11_3_4/src/HiggsAnalysis/CombinedLimit/data/tutorials/parametric_exercise/combinetutorial-2023-parametric/./RooPDF_BKG.cxx";

#endif
