/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "RooPDF_DSCB.h"

#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <Riostream.h>
#include <TMath.h>

#include <cmath>

ClassImp(RooPDF_DSCB);

RooPDF_DSCB::RooPDF_DSCB(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _realHiggsMass,
                        RooAbsReal& _branch_ratio_1,
                        RooAbsReal& _branch_ratio_2)
   : RooAbsPdf(name,title),
   x("x","x",this,_x),
   realHiggsMass("realHiggsMass","realHiggsMass",this,_realHiggsMass),
   branch_ratio_1("branch_ratio_1","branch_ratio_1",this,_branch_ratio_1),
   branch_ratio_2("branch_ratio_2","branch_ratio_2",this,_branch_ratio_2)
{
}

RooPDF_DSCB::RooPDF_DSCB(RooPDF_DSCB const &other, const char *name)
   : RooAbsPdf(other,name),
   x("x",this,other.x),
   realHiggsMass("realHiggsMass",this,other.realHiggsMass),
   branch_ratio_1("branch_ratio_1",this,other.branch_ratio_1),
   branch_ratio_2("branch_ratio_2",this,other.branch_ratio_2)
{
}


double RooPDF_DSCB::evaluate() const 
{
   return RooPDF_DSCB_evaluate(x, realHiggsMass, branch_ratio_1, branch_ratio_2); 
}

void RooPDF_DSCB::computeBatch(double *output, std::size_t size, RooFit::Detail::DataMap const &dataMap) const 
{ 
   std::span<const double> xSpan = dataMap.at(x);
   std::span<const double> realHiggsMassSpan = dataMap.at(realHiggsMass);
   std::span<const double> branch_ratio_1Span = dataMap.at(branch_ratio_1);
   std::span<const double> branch_ratio_2Span = dataMap.at(branch_ratio_2);

   for (std::size_t i = 0; i < size; ++i) {
      output[i] = RooPDF_DSCB_evaluate(xSpan.size() > 1 ? xSpan[i] : xSpan[0],
                               realHiggsMassSpan.size() > 1 ? realHiggsMassSpan[i] : realHiggsMassSpan[0],
                               branch_ratio_1Span.size() > 1 ? branch_ratio_1Span[i] : branch_ratio_1Span[0],
                               branch_ratio_2Span.size() > 1 ? branch_ratio_2Span[i] : branch_ratio_2Span[0]);
   }
} 
void RooPDF_DSCB::translate(RooFit::Detail::CodeSquashContext &ctx) const
{
   ctx.addResult(this, ctx.buildCall("RooPDF_DSCB_evaluate", x, realHiggsMass, branch_ratio_1, branch_ratio_2));
}
