/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOPDF_DSCB_2
#define ROOPDF_DSCB_2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooPDF_DSCB_2 : public RooAbsPdf {
public:
  RooPDF_DSCB_2() {} ; 
  RooPDF_DSCB_2(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _realHiggsMass,
	      RooAbsReal& _alpha_l,
	      RooAbsReal& _alpha_h,
	      RooAbsReal& _n_l,
	      RooAbsReal& _n_h,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _norm);
  RooPDF_DSCB_2(const RooPDF_DSCB_2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooPDF_DSCB_2(*this,newname); }
  inline virtual ~RooPDF_DSCB_2() { }

protected:

  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy alpha_l ;
  RooRealProxy alpha_h ;
  RooRealProxy n_l ;
  RooRealProxy n_h ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy norm ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooPDF_DSCB_2,1) // Your description goes here...
};
 
#endif
