/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooPDF_DBLGAUSS_h
#define RooPDF_DBLGAUSS_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>
#include "RooFormulaVar.h"


class RooPDF_DBLGAUSS : public RooAbsPdf {
public:
   RooPDF_DBLGAUSS() {}
   RooPDF_DBLGAUSS(const char *name, const char *title,        RooAbsReal& _x,
        RooAbsReal& _realHiggsMass,
        RooAbsReal& _branch_ratio_1,
        RooAbsReal& _branch_ratio_2,
        const std::vector<std::vector<double>>& _signal_params,
        bool multiplyBy2);
  
  RooPDF_DBLGAUSS(RooPDF_DBLGAUSS const &other, const char *name=0);
  RooFormulaVar signal_norm(std::string channel_name);


  virtual TObject* clone(const char *newname) const { return new RooPDF_DBLGAUSS(*this, newname); }
  inline virtual ~RooPDF_DBLGAUSS() { }
  void printParameters();

protected:

  RooRealProxy x ;
  RooRealProxy realHiggsMass ;
  RooRealProxy branch_ratio_1 ;
  RooRealProxy branch_ratio_2 ;
  const std::vector<std::vector<double>> signal_params;
  bool multiplyBy2;

  Double_t evaluate() const;

private:

  ClassDef(RooPDF_DBLGAUSS, 1) // Your description goes here...
};

#endif // RooPDF_DBLGAUSS_h